/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '15/03/24 20:56' with Gradle 1.10
 *
 * @author kaakaa_hoe, @date 15/03/24 20:56
 */
public class Library {
    public boolean someLibraryMethod() {
    return true;
    }
}
